# Generated by Django 4.2 on 2023-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
            ],
        ),
    ]
