# Generated by Django 4.2 on 2023-04-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_order_name_order_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='input',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('to', models.CharField(max_length=50)),
                ('fromm', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
